[package]
name = "testing2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "testing2"
crate-type = ["cdylib"]

[dependencies]
petgraph = "0.6.4"
pyo3 = "0.19.0"
serde_json = "1.0.108"
