[package]
name = "tohdl-ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
dyn-clone = "1.0.16"
typed-builder = "0.18.0"
downcast-rs = "1.2.1"
